### ISSUE TITLE
How to use nlcommand?

### ISSUE THREAD

**Issue by moliata** [sympy/sympy_gamma#102]
Hello,
I would like to ask, how to use nlcommand? Because whether I try to use "how to differentiate [derivative goes gere]" in SymPy Gamma, I get a lot of other useless stuff & if I try to search for "interpret" function in SymPy Gamma source code, I can't find it.
Best regards, Ben.

**Comment by moliata** [comment]
On further investigation, I can see, that it has an unknown variable called "math" & that "modifier" variable is not used at all.

**Comment by ylemkimon** [comment]
What do you mean by `nlcommand`?

**Comment by moliata** [comment]
There is a file in app/logic folder called nlcommand, which probably means natural language command. At least that is what this fine does.

**Comment by ylemkimon** [comment]
It seems it’s incomplete and not used anywhere. It probably was mistakenly committed in the #11.

**Comment by moliata** [comment]
Actually it is completed, just a few thing would be needed to be removed.
A) if expression statements should be removed
B) default modifier value should be passed if mod variable is null (default modifier value is actually declared just not passed)
C) we need to use interpret function in logic.py inside SymPy Gamma class.
This feature would be actually pretty cool if it would be used.
