### ISSUE TITLE
How to solve absolute value equations?

### ISSUE THREAD

**Issue by moliata** [sympy/sympy_gamma#103]
Hello, I would like to ask, how should I solve absolute value equations? I can't do that with SymPy Gamma, because it interprets symbols as not real or imaginary.
![screen shot 2018-01-28 at 21 02 34](https://user-images.githubusercontent.com/7127204/35485897-98e0da5e-046e-11e8-8b35-662f52b417f1.png)

**Comment by charlesverge** [comment]
@moliata  Update sympy to the latest version and using solveset is viable option.
 solveset (Abs(x), x)

This can be done in resultsets.py
diff --git a/app/logic/resultsets.py b/app/logic/resultsets.py
index 90004f0..171d8a1 100644
--- a/app/logic/resultsets.py
+++ b/app/logic/resultsets.py
@@ -701,7 +701,7 @@ no_pre_output = lambda *args: ""
 all_cards = {
     'roots': ResultCard(
         "Roots",
-        "solve(%s, {_var})",
+        "solveset(%s, {_var})",
         lambda statement, var, *args: var,
         format_output_function=format_list),

**Comment by moliata** [comment]
@charlesverge how can I update SymPy to the new version without having issues with dependency mpmath?

**Comment by charlesverge** [comment]
@moliata The pip command should be able to install mpmath for you.

**Comment by moliata** [comment]
@charlesverge my instance of SymPy Gamma is on Google App Engine, not on a local machine.
