### ISSUE TITLE
can't calc

### ISSUE THREAD

**Issue by OlgaKarpenko** [sympy/sympy_gamma#114]
integrate(cos(sin(tan(sin(cos(2*(x**sin(x))))))))

**Comment by oscargus** [comment]
No wonder. I doubt it is even possible to compute in analytically. Is it an actual integral that you want to compute? It could be possible to compute it numerically if there are limits.

**Comment by jondo** [comment]
This is a backend topic, so issue should at least be moved to the main sympy issue tracker.
