### ISSUE TITLE
Code not work on  ubuntu digital ocean server

### ISSUE THREAD

**Issue by rsuchit** [sympy/sympy_gamma#121]
i am downloaded the code of sympy-gamma and put on my ubuntu digital ocean server BUT the code can not work  It can occurred the errors.  
How can run sympy-gamma on server? can you help me?

@lidavidm sir,any idea about this ?

**Comment by lidavidm** [comment]
SymPy Gamma is a Django application, I do not believe it will work on Xampp by default. Did the [development instructions](https://github.com/sympy/sympy_gamma#development-server) work for you?

**Comment by rsuchit** [comment]
I have successfully installed on ubuntu digital ocean server but it's automatically close in time interval after 1 or 2 days and need to start again and again on server
i have check process on 8000 port is running but on server its is not working
error was port close unexpectedly
i have coress verified not other project runing on same port
and if there is some exception it will close the application ?
@lidavidm  can you please help me about this?
