### ISSUE TITLE
Link is outdated

### ISSUE THREAD

**Issue by montao** [sympy/sympy_gamma#122]
The link from the readme is not found when we try and follow it

( $ wget https://googleappengine.googlecode.com/files/google_appengine_1.5.1.zip )

It worked for me however to get it started with the cloud sdk, for details see this question and my answer https://stackoverflow.com/questions/58777687/in-python-dev-appserver-py-development-server-not-start/58856138#58856138

**Comment by aktech** [comment]
This is fixed now, as we use docker now and everything happens in docker, abstracted away from the user. (`docker-compose up`)
