### ISSUE TITLE
Deployment on Amazon AWS EC2/Elastic Beanstalk [question] 

### ISSUE THREAD

**Issue by pasdechancee** [sympy/sympy_gamma#125]
Hello,

I wish to deploy this Sympy gamma Django application using AWS cloud solution (with either AWS EC2 directly or AWS Elastic Beanstalk)

I have read tutorials to deploy a Django application there but they all follow the standard Django structure (with manage.py, wsgi.py, etc...).

I also tried to use the appengine developpement build/server and opened a PORT on an EC2 instance but I didn't succeed : (

Could anyone give me a few tips on how to deploy this application on AWS ? Any help would be greatly appreciated ! : )

**Comment by lidavidm** [comment]
This application was built to run on App Engine. Additionally, Gamma isn't necessarily secured against untrusted input and assumes the safety of running in the App Engine sandbox. Running it directly on EC2 would be a risk.

**Comment by pasdechancee** [comment]
Thank you very much for getting back to me !

I played around with AWS EC2 + API Gateway and managed to get it working. However it felt kind of hacky and I wasn't aware of the security risks you mentioned. Eventually, I ended up deploying it on the App Engine as recommended.

Have a great day :)

I'm closing the issue.
