### ISSUE TITLE
Cannot do this integration `integrate(3**tanh(x)/cosh(x)**2,x) `

### ISSUE THREAD

**Issue by newptcai** [sympy/sympy_gamma#126]
If you try this integration in sympygamma

    integrate(3**tanh(x)/cosh(x)**2,x) 

after  a long time you will get an error page.  I guess it's because sympy cannot solve the integral.

**Comment by Mathbone** [comment]
Does not currently generate an error on the live version, but is also not "correct" as per the Wolfram|alpha solution. As suggested, this is probably due to Sympy having not implemented this particular algorithm. I suggest moving the issue to the base Sympy package.

**Comment by oscarbenjamin** [comment]
Thanks for reporting this. As @Mathbone says this should be opened as an issue with sympy rather than sympygamma.
