### ISSUE TITLE
ImportError: cannot import name 'LogRule'

### ISSUE THREAD

**Issue by anand-parmar** [sympy/sympy_gamma#131]
Hi,

i am using intsteps.py file https://github.com/sympy/sympy_gamma/blob/master/app/logic/intsteps.py

There i am facing this error
```
 File "E:\MAMP\htdocs\bitwise\stemsol\intsteps.py", line 8, in <module>
    from sympy.integrals.manualintegrate import (
ImportError: cannot import name 'LogRule'
```

**Comment by asmeurer** [comment]
SymPy Gamma currently works against a rather old version of SymPy. It needs to be updated to work with the latest version.

**Comment by anand-parmar** [comment]
Hi,

I am using 
```
Python 3.6.5

Name: sympy
Version: 1.5.1
Summary: Computer algebra system (CAS) in Python
Home-page: https://sympy.org
Author: SymPy development team
Author-email: sympy@googlegroups.com
License: BSD
Location: c:\users\digital39\appdata\local\programs\python\python36-32\lib\site-packages
Requires: mpmath
Required-by:
```

i am using latest version

**Comment by manish182** [comment]
Use the previous version (from 2014) of manualintegrate.py and it will work fine

**Comment by anand-parmar** [comment]
Yeas @manish182 ,
I have changed version to '0.7.5' 
`pip install sympy==0.7.5`

Now it is working.
