### ISSUE TITLE
Make the app compatible with Python 3

### ISSUE THREAD

**Issue by aktech** [sympy/sympy_gamma#151]
Currently the app runs on Google App Engine's Python 2 Runtime. We need to migrate to Python 3 runtime.

This cannot happen in one go. It would happen over multiple steps, meanwhile we need to make the app compatible with Python 3 as well supporting Python 2, to allow the incremental update.

**Comment by asmeurer** [comment]
Would it be better to update to Python 3 first or to try to update to a newer version of SymPy first?

**Comment by aktech** [comment]
I was thinking to directly support the latest version, via the requirements file in Python 3 runtime of GAE instead, as that will be less work than temporarily supporting a newer version, which might require some plumbing and we might need to do that plumbing again while updating to the latest version, so maybe its better to do that once.

**Comment by asmeurer** [comment]
I think a lot of the code will require updating to work with the latest SymPy version.

**Comment by aktech** [comment]
Oh, I see. In that case we can start with sympy first.

**Comment by asmeurer** [comment]
Actually I think we have to update Python first, since the latest version of SymPy doesn't support Python 2. Otherwise we have to update SymPy to 1.5.1 (the last version to support Python 2), then update to Python 3, then update SymPy again to 1.6.

**Comment by aktech** [comment]
This is done and deployed.
