### ISSUE TITLE
Upgrade SymPy to latest version

### ISSUE THREAD

**Issue by aktech** [sympy/sympy_gamma#155]
The application will soon run on Python3 runtime #154 This needs to be done after that. This involves updating the version in requirements.txt and testing everything.

**Comment by satels** [comment]
What is last supported version of sympy?

**Comment by aktech** [comment]
Currently it is: https://github.com/sympy/sympy_gamma/blob/e4d4523a3afa3d12867513644201006d2fb964c1/requirements.txt#L12

The plan is to upgrade it to 1.6
