### ISSUE TITLE
Add report an issue button/link

### ISSUE THREAD

**Issue by aktech** [sympy/sympy_gamma#163]
There isn't an obvious way for users to open issues on the Gamma, it would very useful to have a link/button somewhere easily visible linking to: https://github.com/sympy/sympy_gamma/issues/new

**Comment by asmeurer** [comment]
I've noticed already that people open issues on Gamma/Live that are actually SymPy issues. Also they don't always tend to be high quality issues. We can add this, but we should watch it and if it generates a lot of junk issues we should consider removing it.

**Comment by asmeurer** [comment]
Also there's already a link to the GitHub at the bottom, so people who know what they are doing can already find this issue tracker.

**Comment by aktech** [comment]
> Also there's already a link to the GitHub at the bottom, so people who know what they are doing can already find this issue tracker.

Makes sense.
