### ISSUE TITLE
Failure to compute the integral with parameter manual=True

### ISSUE THREAD

**Issue by jzy3d** [sympy/sympy_gamma#190]
Thank you for this excellent platform!

I would like to report a failing case :

`integrate(t/sqrt(1-t**2), manual=True)` leads to the Oops page. Reproduce [here](https://gamma.sympy.org/input/?i=integrate%28t%2Fsqrt%281-t**2%29%2C+manual%3DTrue%29).

Same goes for `integrate(t/sqrt(1-t**2),t , manual=True)`. Reproduce [here](https://gamma.sympy.org/input/?i=integrate%28t%2Fsqrt%281-t**2%29%2Ct+%2C+manual%3DTrue%29)

Thanks for your feedback!

**Comment by eagleoflqj** [comment]
Thanks for reporting.
This project is currently not maintained. I fixed the bug in my fork [SymPy Beta](https://github.com/eagleoflqj/sympy_beta)

**Comment by jzy3d** [comment]
I confirm it works. Congratulation, you are doing great work!
