### ISSUE TITLE
function "print_U" in intsteps.py file is not working in the older version of python.

### ISSUE THREAD

**Issue by mandavavinay** [sympy/sympy_gamma#61]
All,
I am using gamma.sympy on older version of python which is 2.6. All the function are working fine. Only "print_U" method in intsteps.py file is not supported in 2.6 version. Particular the below syntax in the "print_U" methods in not supporting 
def print_U(self, rule):
        with self.new_step(), self.new_u_vars() as (u, du):

So, how can i convert this entire method to support 2.6 version. Or is there any older version of Sympy.gamma exist to support older version of python.

**Comment by sahilshekhawat** [comment]
@mandavavinay sympy_gamma is a wolframalpha like web app based on SymPy. This issue should be open in [SymPy's Issue tracker](https://github.com/sympy/sympy/issues)

**Comment by mandavavinay** [comment]
@sahilshekhawat The file I mentioned is sympy_gamma based, it exits at sympy_gamma/app/logic/intsteps.py. In this file I found the below method 
def print_U(self, rule):
with self.new_step(), self.new_u_vars() as (u, du):
and its not supported by older version of python (i.e 2.6)
Thats why i raised the issue in sympy_gamma.
