### ISSUE TITLE
incorrect steps, but correct output for integrate(x*cos(x**2))

### ISSUE THREAD

**Issue by ncop** [sympy/sympy_gamma#65]
![capture](https://cloud.githubusercontent.com/assets/13977870/10260775/c989feec-69a7-11e5-9027-7b8397900e1f.PNG)

**Comment by Curious72** [comment]
@hargup Can i have a look at this?

**Comment by asmeurer** [comment]
You might check if the unmerged https://github.com/sympy/sympy_gamma/pull/60 addresses this.

**Comment by ashutoshsaboo** [comment]
@asmeurer  Could you please review PR #69 ? Thanks!
