### ISSUE TITLE
How to write for this series integral problem on SymPy Gamma? (i need solution steps)

### ISSUE THREAD

**Issue by ncop** [sympy/sympy_gamma#83]
![image](https://cloud.githubusercontent.com/assets/13977870/14554563/075a4fec-0318-11e6-910a-29172ba44b26.png)

**Comment by nicoguaro** [comment]
Your expression is not clear enough. Where did you get this integral from?

**Comment by hargup** [comment]
agree with @nicoguaro the issue is not clear, @ncop can please provide more details.
